name: Docker Build and Push

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Required to push to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Docker tag
        id: tag
        run: |
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            # Use Git tag (e.g., v1.0.0) for Docker tag
            TAG_NAME=${GITHUB_REF#refs/tags/}
          else
            # Use 'latest' for master branch commits
            TAG_NAME="latest"
          fi
          echo "DOCKER_TAG=${TAG_NAME}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/eripa/manymine:${{ steps.tag.outputs.DOCKER_TAG }}
